# Generated by Django 4.2 on 2025-04-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_landing', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='opcion',
            constraint=models.UniqueConstraint(fields=('nombre',), name='Opcion no repetida'),
        ),
    ]
