# Generated by Django 4.2 on 2025-04-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_landing', '0002_opcion_opcion_no_repetida'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='etiqueta',
            field=models.CharField(default='lugar', max_length=50),
            preserve_default=False,
        ),
    ]
